spring:
  application:
    name: orderflow

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/orderflow}
    username: ${SPRING_DATASOURCE_USERNAME:orderflow}
    password: ${SPRING_DATASOURCE_PASSWORD:orderflow}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:orderflow}
    password: ${SPRING_RABBITMQ_PASSWORD:orderflow}

orderflow:
  payment:
    gateway:
      url: ${PAYMENT_GATEWAY_URL:http://localhost:8090}
      connect-timeout: 2s
      read-timeout: 3s

resilience4j:
  retry:
    instances:
      paymentGateway:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
  circuitbreaker:
    instances:
      paymentGateway:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
