spring:
  application:
    name: orderflow

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/orderflow}
    username: ${SPRING_DATASOURCE_USERNAME:orderflow}
    password: ${SPRING_DATASOURCE_PASSWORD:orderflow}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:orderflow}
    password: ${SPRING_RABBITMQ_PASSWORD:orderflow}
